### ISSUE TITLE
국가 공휴일과 사고량(사상자 집계)의 상관관계

### ISSUE THREAD

**Issue by pmz-q** [pmz-q/est_wassup_01#11]
- 국가 공휴일에 사고량 증가
- 국가 공휴일의 전날, 시작날, 마지막날, 마지막 날 다음날 에 사상자의 수가 증가할 것이다.
- 국가 공휴일의 전, 시작, 마지막, 마지막의 다음 날 사고량 대비 사상자의 수가 많을 것이다. (ECLO 증가)

https://www.yna.co.kr/view/AKR20230925056400530

**Comment by cmsk6405** [comment]
유의미할 만큼의 차이가 존재 하지 않는 것 같음
