### ISSUE TITLE
계절에 따른 가설

### ISSUE THREAD

**Issue by electronicguy97** [pmz-q/est_wassup_01#8]
계절에 따라 사고량이 다른지 확인

**Comment by DARNIM-LEE** [comment]
계절에 따라 크게 차이가 나지 않는다
겨울(3,254) < 여름(3,590) <봄(3,731) < 가을(3,961) 이고 사망사고건수(사망자)는
여름 25(26) < 봄,겨울 27(28) < 가을30(30) 이다

**Comment by electronicguy97** [comment]
저희는 자료 위치를 알아서 괜찮지만 혹시 모를 출처도 필요하다고 생각합니다 
자료 조사는 깔끔하게 정리된거 같아 고생하셨습니다 좋아요~
출처 : https://taas.koroad.or.kr/web/umt/lmt/initLogin.do
