### ISSUE TITLE
민식이법 이후 어린이 보호구역 사고 증가 기사

### ISSUE THREAD

**Issue by DARNIM-LEE** [pmz-q/est_wassup_01#9]

**Comment by DARNIM-LEE** [comment]
2020년 어린이보호구역내 어린이 사고는 25건
2021년 어린이보호구역내 어린이 사고는 33건 으로 8건 늘었다

**Comment by electronicguy97** [comment]
자료 출처도 알려주시면 좋을것 같습니다

**Comment by DARNIM-LEE** [comment]
https://blog.naver.com/jsyang7735/222748788192 - 국회의원 양정숙

https://r.search.yahoo.com/_ylt=Awrjc3SwLWdlFsIHlhNXNyoA;_ylu=Y29sbwNncTEEcG9zAzEEdnRpZAMEc2VjA3Ny/RV=2/RE=1701289521/RO=10/RU=https%3a%2f%2fwww.idaegu.com%2fnewsView%2fidg202303260019/RK=2/RS=9Q3mpFOFbXv7UQzM9HNFtDmlxTE-
대구일보 - 이승엽기자
